# Generated by Django 3.1.1 on 2020-09-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snsproject', '0002_auto_20200923_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20, verbose_name='IPアドレス')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snsproject.snsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
