# Generated by Django 3.1.1 on 2020-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsproject', '0004_auto_20200924_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low'), ('complete', 'primary')], max_length=50),
        ),
    ]
