# Generated by Django 3.1.1 on 2020-10-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsproject', '0007_todomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
